
SET XACT_ABORT ON
SET ARITHABORT ON
GO

BEGIN TRANSACTION


INSERT INTO [dbo].[Licencia] ([Licencia], [Clave]) 
VALUES ('t580E+3hYvzUVCebABNMoX3Xzu9Nk/KnKP+LgpBJUOM=', 'jP0Ilb6XCJVE1gulqCAMuJf0sFha0/aRAailrosAaa0=')

COMMIT TRANSACTION